const forGenderData = {
	m: "men",
	me: "men",
	men: "men",
	male: "men",
	gentle: "men",
	gentlemen: "men",
	fem: "female",
	female: "female",
	la: "women",
	lad: "women",
	lady: "women",
	ladies: "women",
	wo: "women",
	wom: "women",
	women: "women",
};

const categories = {
	common: {
		t: "tshirts",
		ts: "tshirts",
		tsh: "tshirts",
		tshirt: "tshirts",
		tshirts: "tshirts",
		casual: "casual_shirts",
		casual_sh: "casual_shirts",
		formal_shirts: "formal_shirts",
		blazers: "blazers",
		ja: "jackets",
		jack: "jackets",
		jackets: "jackets",
		sweaters: "sweaters",
		sweatshirts: "sweatshirts",
		je: "jeans",
		jea: "jeans",
		jean: "jeans",
		de: "jeans",
		denim: "jeans",
		denims: "jeans",
		trousers: "casual_trousers",
		casual_trousers: "casual_trousers",
		formal_trusers: "formal_trusers",
		track_pants: "track_pants",
		sho: "casual_shoes",
		shoes: "casual_shoes",
		casual_shoes: "casual_shoes",
		formal_shoes: "formal_shoes",
		boo: "boots",
		boots: "boots",
		sn: "sneakers",
		snea: "sneakers",
		sneakers: "sneakers",
	},
	men: {
		trunk: "trunk",
		boxer: "boxer",
	},
	women: {
		kurta: "kurta_and_suits",
		"kurta suits": "kurta_and_suits",
		kur: "kurtis",
		kurti: "kurtis",
		kurtis: "kurtis",
		legg: "leggings",
		leggings: "leggings",
		salwar: "salwar_and_churidar",
		salwar_and_churidar: "salwar_and_churidar",
		skirts: "skirts",
		pl: "plazzos",
		plaz: "plazzos",
		plazzos: "plazzos",
		sarees: "sarees",
		lehnga_cholis: "lehnga_cholis",
		dupattas: "dupattas",
		shawls: "shawls",
		capris: "capris",
		shorts: "shorts",
		bra: "bra",
		briefs: "briefs",
		shapewear: "shapewear",
		swimwear: "swimwear",
		thermals: "thermals",
		fla: "flats",
		flats: "flats",
		heels: "heels",
	},
};

export { forGenderData, categories };
